image: Ubuntu

environment:
  APPVEYOR_CONSOLE_DISABLE_PTY: true

stack: jdk 8

build_script:
- sh: ./mvnw --no-transfer-progress compile

test_script:
- sh: ./mvnw --no-transfer-progress test surefire-report:report-only

artifacts:
  - path: target/site/surefire-report.html
    name: Test Results